export const priceFields = {
  "Ulike taktekker": {
    "Enkeltkrummet takstein": {},
    "Glassert takstein": {},
    "Flat takstein": {},
    "Dobbelkrummet takstein": {},
    Shingel: {},
    "Trapes plater": {},
    Flattak: {},
    Bølgeblikk: {},
    Decra: {},
    Integrerte: {},
  },
  "Arbeid fra elektriker": {
    "Føring fra tak til inverter": {},
    "Sikring + opplegg til inverter": {},
    "Dokumentasjon/søknad til nettselskap": {},
    "Stillase* (gjelder for en side)": {},
  },
  "Tilleggsarbeid fra elektriker": {
    "Stillase* (gjelder for en side)": {},
    "Tillegg for takstein som er skrudd (pr. panel)": {},
    "Tillegg for jobbing på bratte tak (over 35°)": {},
    "Tillegg for paneler på flere bygninger*": {},
    "DC kabler i rør lagt i ferdig grøft (pr. m)": {},
    "Tilførselkabel til inverter utover 15m": {},
    "Tillegg for gjennomføring betongvegg pr. hull (opp til 25mm. Ikke kjerneborring)":
      {},
    "Overspenningsvern ferdig montert": {},
  },

  Paneler: {
    "Aiko 440W All black, Mono - 2 generasjon": {},
    "Trina Solar 415W All black": {},
  },
  Festemateriell: {
    "Takstein - VG Solar/Kina": {},
    "Fasade - Rauli/Finland": {},
    "Trapesplater - MS/Tyskland": {},
    "Flatt øst/vest - MS/Tyskland": {},
    "Integrerte ": {},
    "Takstein - MS/Tyskland": {},
  },
  "Inverter string 230V": {
    "Deye 6kW": {},
    "Deye 8kW": {},
    "Deye 15kW": {},
    "Deye 20kW": {},
    "Deye 25kW": {},
    "Deye 30kW": {},
    "Deye 50kW": {},
  },
  "Inverter string 400V": {
    "Deye 6kW": {},
    "Deye 8kW": {},
    "Deye 15kW": {},
    "Deye 20kW": {},
    "Deye 25kW": {},
    "Deye 30kW": {},
    "Deye 50kW": {},
  },
  "Inverter hybrid (til batterier) 230V": {
    "Deye 7,3kW": {},
    "SunSynk 29kW": {},
  },
  "Inverter hybrid (til batterier) 400V": {
    "Deye 12kW": {},
    "SunSynk 50kW": {},
  },
  Batteri: {
    "Lavvolt - VW 5,12kWt": {},
    "Lavvolt - VW 10,24kWt": {},
    "Lavvolt - VW 15,36kWt": {},
    "Lavvolt - VW 20,58kWt": {},
    "Høyvolt - SS 61.44kWt": {},
  },
};

export const categoryFields = {
  "Ulike taktekker": [
    "Snekker kostnad pr. panel",
    "Påslag elektriker %",
    "Påslag i Kr",
    "Total eks. mva",
    "Total inkl. mva",
  ],
  "Arbeid fra elektriker": [
    "Kostnad pr.",
    "Påslag elektriker %",
    "Påslag i Kr",
    "Total eks. mva",
    "Total inkl. mva",
  ],
  "Tilleggsarbeid fra elektriker": [
    "Kostnad pr.",
    "Påslag elektriker %",
    "Påslag i Kr",
    "Total eks. mva",
    "Total inkl. mva",
  ],
  // skal stå paneler
  Paneler: [
    "Kostnad pr.",
    "Påslag elektriker %",
    "Påslag i Kr",
    "Total eks. mva",
    "Total inkl. mva",
  ],
  Festemateriell: [
    "Kostnad pr.",
    "Påslag elektriker %",
    "Påslag i Kr",
    "Total eks. mva",
    "Total inkl. mva",
  ],
  "Inverter string 230V": [
    "Kostnad pr.",
    "Påslag elektriker %",
    "Påslag i Kr",
    "Total eks. mva",
    "Total inkl. mva",
  ],
  "Inverter string 400V": [
    "Kostnad pr.",
    "Påslag elektriker %",
    "Påslag i Kr",
    "Total eks. mva",
    "Total inkl. mva",
  ],
  "Inverter hybrid (til batterier) 230V": [
    "Kostnad pr.",
    "Påslag elektriker %",
    "Påslag i Kr",
    "Total eks. mva",
    "Total inkl. mva",
  ],
  "Inverter hybrid (til batterier) 400V": [
    "Kostnad pr.",
    "Påslag elektriker %",
    "Påslag i Kr",
    "Total eks. mva",
    "Total inkl. mva",
  ],
  Batteri: [
    "Kostnad pr.",
    "Påslag elektriker %",
    "Påslag i Kr",
    "Total eks. mva",
    "Total inkl. mva",
  ],
};
